### ISSUE TITLE
Migrate to `rem` for font size

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-starter-minima#4]
Currently, I wrote CSS that uses `px` for font-size but having them in `rem` is a good practice for accessibility.

*Note: This issue is especially for beginners in the web so if you're comfortable in contributing to open-source, I will highly suggest to check out other issues in this repository or other repositories under this organization*

If you have any questions, you can drop them in comments.

**Comment by AnkitJuyal009** [comment]
Hey! @saurabhdaware I would like to contribute.
Please assign this to me.
Thanks!

**Comment by saurabhdaware** [comment]
Hi @AnkitJuyal009 you can go ahead with this. Let me know if you need any help. Thanks!

**Comment by AnkitJuyal009** [comment]
Hey! @saurabhdaware Do you want me to commit changes in master branch? or want me to create a new branch then commit?

**Comment by saurabhdaware** [comment]
Either way it is fine but It is a good practice generally to commit to a new branch and then send Pull Request.

**Comment by AnkitJuyal009** [comment]
Hey @saurabhdaware I've made my pull request on another branch.
Thanks for assigning me. (It's my first PR)
Thank You!

**Comment by saurabhdaware** [comment]
Congratulations on your first PR @AnkitJuyal009 :tada: Thank you so much and have a great Hacktoberfest!
